# Generated by Django 4.0.5 on 2023-02-09 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReceiveImageTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remoteAddr', models.CharField(max_length=32, verbose_name='请求地址')),
                ('algCode', models.CharField(max_length=8, verbose_name='算法类型')),
                ('analyseId', models.CharField(max_length=32, verbose_name='分析ID')),
                ('imageData', models.TextField(verbose_name='图片数据')),
                ('ruleData', models.TextField(verbose_name='规则详情')),
                ('status', models.CharField(choices=[('init', '未处理'), ('pending', '处理中'), ('done', '已完成')], default='init', max_length=8, verbose_name='状态')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReceiveVideoTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remoteAddr', models.CharField(max_length=32, verbose_name='请求地址')),
                ('algCode', models.CharField(max_length=8, verbose_name='算法类型')),
                ('algParams', models.CharField(blank=True, max_length=32, null=True, verbose_name='参数')),
                ('analyseId', models.CharField(max_length=32, verbose_name='分析ID')),
                ('startTime', models.CharField(max_length=32, verbose_name='start time')),
                ('endTime', models.CharField(max_length=32, verbose_name='end time')),
                ('interval', models.CharField(max_length=8, verbose_name='interval')),
                ('command', models.CharField(max_length=64, verbose_name='command')),
                ('videoInfo', models.TextField(verbose_name='video info')),
                ('rule', models.TextField(verbose_name='规则详情')),
                ('status', models.CharField(choices=[('init', '未处理'), ('pending', '处理中'), ('error', '已失败'), ('done', '已完成')], default='init', max_length=8, verbose_name='状态')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
